-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 13:25:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoServico` (
  `IdTipo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(50) NOT NULL COMMENT 'Tipos: consertados ou revisões  periódicas',
  PRIMARY KEY (`IdTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `IdEquipe` INT NOT NULL AUTO_INCREMENT,
  `NomeEquipe` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carro` (
  `IdCarro` INT NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(50) NOT NULL,
  `Placa` VARCHAR(12) NOT NULL,
  `IdCliente` INT NOT NULL,
  `IdTipo` INT NOT NULL,
  `IdEquipe` INT NOT NULL,
  PRIMARY KEY (`IdCarro`),
  INDEX `fk_Carro_Cliente_idx` (`IdCliente` ASC) VISIBLE,
  INDEX `fk_Carro_Tipo Serviço1_idx` (`IdTipo` ASC) VISIBLE,
  INDEX `fk_Carro_Equipe1_idx` (`IdEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Carro_Cliente`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_Tipo Serviço1`
    FOREIGN KEY (`IdTipo`)
    REFERENCES `mydb`.`TipoServico` (`IdTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_Equipe1`
    FOREIGN KEY (`IdEquipe`)
    REFERENCES `mydb`.`Equipe` (`IdEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanicos` (
  `IdMecanicos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Endereço` VARCHAR(200) NOT NULL,
  `IdEquipe` INT NOT NULL,
  PRIMARY KEY (`IdMecanicos`),
  INDEX `fk_Mecanicos_Equipe1_idx` (`IdEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanicos_Equipe1`
    FOREIGN KEY (`IdEquipe`)
    REFERENCES `mydb`.`Equipe` (`IdEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialidades` (
  `IdEspecialidades` INT NOT NULL AUTO_INCREMENT,
  `Especialidade` VARCHAR(80) NOT NULL,
  `IdMecanicos` INT NOT NULL,
  PRIMARY KEY (`IdEspecialidades`),
  INDEX `fk_Especialidades_Mecanicos1_idx` (`IdMecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidades_Mecanicos1`
    FOREIGN KEY (`IdMecanicos`)
    REFERENCES `mydb`.`Mecanicos` (`IdMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusOrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusOrdemServico` (
  `IdStatusOrdemServico` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`IdStatusOrdemServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autorizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autorizacao` (
  `IdAutorizacao` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(50) NOT NULL COMMENT 'Autorizado pelo cliente\nNão autorizado pelo cliente',
  PRIMARY KEY (`IdAutorizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdemServico` (
  `IdOrdemServico` INT NOT NULL AUTO_INCREMENT,
  `DataEmissao` DATE NOT NULL,
  `DataConclusao` DATE NULL,
  `ValorServico` FLOAT NULL,
  `IdStatusOrdemServico` INT NOT NULL,
  `IdEquipe` INT NOT NULL,
  `IdAutorizacao` INT NOT NULL,
  PRIMARY KEY (`IdOrdemServico`),
  INDEX `fk_OS_Status OS1_idx` (`IdStatusOrdemServico` ASC) VISIBLE,
  INDEX `fk_OS_Equipe1_idx` (`IdEquipe` ASC) VISIBLE,
  INDEX `fk_OS_Autorização1_idx` (`IdAutorizacao` ASC) VISIBLE,
  CONSTRAINT `fk_OS_Status OS1`
    FOREIGN KEY (`IdStatusOrdemServico`)
    REFERENCES `mydb`.`StatusOrdemServico` (`IdStatusOrdemServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Equipe1`
    FOREIGN KEY (`IdEquipe`)
    REFERENCES `mydb`.`Equipe` (`IdEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Autorização1`
    FOREIGN KEY (`IdAutorizacao`)
    REFERENCES `mydb`.`Autorizacao` (`IdAutorizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicos` (
  `IdServicos` INT NOT NULL AUTO_INCREMENT,
  `Servico` VARCHAR(200) NOT NULL,
  `Valor` FLOAT NOT NULL,
  `IdOrdemServico` INT NOT NULL,
  PRIMARY KEY (`IdServicos`),
  INDEX `fk_Serviços_OS1_idx` (`IdOrdemServico` ASC) VISIBLE,
  CONSTRAINT `fk_Serviços_OS1`
    FOREIGN KEY (`IdOrdemServico`)
    REFERENCES `mydb`.`OrdemServico` (`IdOrdemServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
